metabase:
  container_name: dafmetabase
  image: metabase/metabase:latest
  links:
      - postgresmetabase
  ports:
      - "3000:3000"
  environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgresmetabase
postgresmetabase:
  container_name: postgresmetabase
  image: postgresmetabase:1.0.0
  ports:
      - "5432:5432"
